config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :dogs, only: [:show, :index, :create, :new] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :destroy, :update]

  namespace :owner do
    resources :bookings, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dog
  belongs_to :user

  STATUS = ["pending", "cancelled", "accepted", "rejected", "completed"]
  validates :status, inclusion: { in: STATUS }

  validate :start_time_cannot_be_in_the_past
  validate :end_time_cannot_be_before_start_time

  def pending?
    status == 'pending'
  end

private

  def start_time_cannot_be_in_the_past
    errors.add(:start_time, "can't be in the past") if start_time < Date.today
  end

  def end_time_cannot_be_before_start_time
    errors.add(:end_time, "can't be before the start time") if end_time < start_time
  end


end

app/models/dog.rb
class Dog < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :reviews
  has_many :bookings
  has_many_attached :photos

  validates :name, presence: true, length: { within: 3..20 }
  validates :age, presence: true, numericality: { greater_than_or_equal_to: 0 }
  BREEDS = ["Shiba", "Corgie", "Husky", "Daschund", "Poodle"]
  validates :breed, presence: true, inclusion: { in: BREEDS }
  validates :price, presence: true
    # acts_as_taggable_on :tags

  pg_search_scope :search_by,
  against: [ :name, :breed, :age ],
  associated_against: {
    user: [ :name, :address ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dog
  belongs_to :user
  validates :rating, presence: true, numericality: { in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dogs, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_owner, through: :dogs, source: :bookings


  # geocoder logic for map
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  # devise settings for log-in / register logic
  validates :name, presence: true, length: { within: 3..20 }
  validates :age, numericality: { greater_than_or_equal_to: 18 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def index
    @user = current_user
    @bookings = @user.bookings
    @owner_bookings = @user.bookings_as_owner
  end

  def create
    @user = current_user
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new(booking_params)
    @booking.dog = @dog
    @booking.user = @user
    @booking.status = "pending"
    # array = [@booking.start_time, @booking.end_time]
    # raise
    @booking.total_price = @dog.price * ((@booking.end_time - @booking.start_time) / 60 / 60)
    if @booking.save
      redirect_to bookings_path
    else
      redirect_to bookings_path, status: :unprocessable_entity
    end
  end

  def new
    @booking = Booking.new(booking_params)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      # render # where was the booking update form?
      redirect_to bookings_path, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :dog_id, :user_id, :status)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index

    if params[:query].present?
      @dogs = Dog.search_by(params[:query])
    else
      @dogs = Dog.all
    end
    @users = User.where(id: @dogs.extract_associated(:user).uniq.pluck(:id))

    @markers = @users.geocoded.map do |user|
      {
        latitude: user.latitude,
        longitude: user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {dogs: user.dogs}),
        marker_html: render_to_string(partial: "marker", locals: {dogs: user.dogs})
      }
    end
  end

  def show
    @dog = Dog.find(params[:id])
    @booking = Booking.new
  end

  def create
    @owner = current_user
    @dog = Dog.new(dog_params)
    @dog.user = @owner
    if @dog.save
      redirect_to dog_path(@dog)
      puts 'saved'
    else
      render 'new', status: :unprocessable_entity
      puts 'not saved'
    end
  end

  def new
    @owner = current_user
    @dog = Dog.new
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :age, :breed, :price, :description, photos: [])
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home

    if params[:query].present?
      @dogs = Dog.search_by(params[:query])
    else
      @dogs = Dog.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end

  def bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="mx-5">
  <h1 class="mt-3"><%= "#{@user.name}'s Bookings" %></h1>
  <% if @bookings.count > 0 %>
    <div class="row">
      <% @bookings.each do |booking| %>
        <div class="col-6">
          <%= render 'pages/booking_card', booking: booking %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p><%= "You have no bookings!"%></p>
  <% end %>
  <% if  @owner_bookings.present?%>
    <h2 class="mt-3">Your Dog's Bookings</h2>
    <div class="bookings">
      <% @owner_bookings.each do |booking| %>
        <div class="booking card-booking">
          <div class='booking-left'>
            <!-- if you're using cloudinary and activestorage -->
            <%= image_tag 'stan.jpg', alt: "text", class: '', width: '100px', height: '50px' %>
            <div class="booking-info">
              <div class="booking-info-title">
                <%= booking.user.name %> would like to book <%= booking.dog.name %>
              </div>
              <div class="booking-info-details">
                <i class="fa-regular fa-calendar"></i> <strong><%= booking.start_time %></strong> (<%= booking.start_time.strftime('%l:%M %p') %>) - <strong><%= booking.end_time %></strong> (<%= booking.end_time.strftime('%l:%M %p') %>)
                <p>Total Price: ¥<%= booking.total_price %></p>
              </div>
            </div>
          </div>
          <div class="booking-actions">
            <% if booking.pending? %>
              <%= simple_form_for booking do |f| %>
                <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
                <%= f.submit 'Accept', class: 'button-choice-yes' %>
              <% end %>
              <%= simple_form_for booking do |f| %>
                <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
                <%= f.submit 'Reject', class: 'button-choice-no' %>
              <% end %>
            <% else %>
              <p class='booking-tag'><%= booking.status %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/dogs/_info_window.html.erb
<%# <%= image_tag dogs[0].photos.all[0], alt: "Dog picture", class: "card-img img-fluid rounded-top-4" %>
<div class="dog_card">
  <div class="card rounded-4">
    <div class="card-body p-0">
      <%# <%= image_tag dog.photos.all[0], alt: "Dog picture", class: "card-img img-fluid" %>
       <%= cl_image_tag dogs[0].photos[0].key, alt: "..." , class: "card-img img-fluid"%>
    </div>
    <div class="bio ms-1 dog_card">
      <p class="mb-0 black-bold"> <strong><%= dogs[0].name %></strong> </p>
      <p class="black-semi-bold">¥<%=dogs[0].price%>0 per hour</p>
    </div>
  </div>
  <%= link_to "", dog_path(dogs[0]), class: "card-dog-link" %>
</div>

app/views/dogs/_marker.html.erb
<%= image_tag dogs[0].photos.all[0], alt: "Dog picture", class: "rounded-circle object-fit-cover shadow border border-3 border-info", width: '65px', height: '65px' %>

app/views/dogs/create.html.erb
<h1>Dogs#create</h1>
<p>Find me in app/views/dogs/create.html.erb</p>

app/views/dogs/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-7 mt-3">
      <div class="row">
        <% @dogs.order(:id).each do |dog| %>
          <div class="col-4">
            <%= render 'pages/index_card', dog: dog %>
          </div>
        <% end %>
        <% if @dogs.empty? %>
          <div class="container">
            <h1>No results found!</h1>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-5 ps-0 px-0">
      <div style="width: 100%; height: calc(100vh - 70px); position: sticky; top: 70px; left: 0;"
           data-controller="map"
           data-map-markers-value="<%= @markers.to_json %>"
           data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/dogs/new.html.erb
  <div class="d-flex justify-content-center form-dog mt-2">
    <%= simple_form_for @dog do |f| %>
    <div class="d-flex justify-content-center">
      <h1>Register your Bark Buddy!</h1>
    </div>
    <div class="parent d-flex mt-2">
      <div class="left d-flex flex-column w-50 p-1">
        <%= f.input :name, placeholder: "What's your dog's name?" %>
        <%= f.input :age, placeholder: "What's your dog's age?" %>
        <%= f.input :breed, collection: Dog::BREEDS, include_blank: false%>
        <%= f.input :price, placeholder: "Rate per hour", label: 'Price (In JPY)' %>
      </div>
      <div class="right d-flex flex-column w-50 p-1">
        <%= f.input :description, placeholder: "What's your dog like?", input_html: { rows: '8' } %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      </div>
    </div>
        <div class="d-flex justify-content-center">
          <%= f.submit class: "reserve-btn w-50", value: 'Create Dog' %>
        </div>
    <% end %>
  </div>

app/views/dogs/show.html.erb
<div class="container">
  <!-- Dog information -->
  <div class="d-flex justify-content-between my-2">
    <h1><%= @dog.name %></h1>
    <button type="button" class="btn"><i class="fa-regular fa-heart"></i> Save</button>
  </div>
  <!-- Dog images -->
  <div class="row dog-grid">
    <div class="col-6 p-1 row-1">
      <%= image_tag @dog.photos.all[0], alt: "text", class: "w-100 p-1" %>
    </div>
    <div class="col-6 p-1">
      <div class="row">
        <div class="col-6 d-flex flex-column justify-content-between p-1 row-2">
          <%= image_tag @dog.photos.all[1], alt: "text", class: "w-100 h-50 pb-1" %>
          <%= image_tag @dog.photos.all[2], alt: "text", class: "w-100 h-50" %>
        </div>
        <div class="col-6 d-flex flex-column justify-content-between p-0 pb-1 pt-1 row-2">
          <%= image_tag @dog.photos.all[3], alt: "text", class: "w-100 h-50 pb-1" %>
          <%= image_tag @dog.photos.all[4], alt: "text", class: "w-100 h-50" %>
        </div>
      </dp-0 itv>
    </div>
  </div>
</div>
<!-- Dog details -->
<div class="mt-4">
  <div class="row h-100">
    <div class="col-8 my-2">
      <!-- Breed and age -->
      <p class='mb-0'> <i class="fa-solid fa-dog"></i> <%= @dog.breed.capitalize %></p>
      <p class='mb-0'> <i class="fa-solid fa-calendar-days"></i> <%= @dog.age %> years old </p>
      <!-- Owner information -->
      <div class="row border-top mt-2">
        <div class="d-flex align-items-center mt-2">
          <%= image_tag 'stan.jpg', alt: "text", class: 'rounded-circle avatar me-2', width: '40px', height: '40px' %>
          <%= @dog.user.name %>
        </div>
      </div>
      <!-- Description -->
      <div class="row border-top mt-2">
        <div class="col-12 my-2">
          <%= @dog.description %>
        </div>
      </div>
    </div>
    <!-- Booking and price -->
    <div class="col-4 text-center justify-content-center" data-controller="booking-price" data-booking-price-price-value="<%= @dog.price %>"  id="booking-box">
      <div class="row h-25 align-items-center">
        <p class='mb-0 black-bold'>¥<%= @dog.price %>0 per hour</p>
      </div>
      <!-- Date picker -->
      <div class="row justify-content-center mx-2">
        <%= simple_form_for([@dog, @booking]) do |f| %>
          <div class="d-flex bg-light border rounded-4">
            <%= f.input :start_time, placeholder: Date.today.to_s, as: :string, input_html: { value: Date.today, data: { controller: "datepicker", booking_price_target: 'start_date', action: 'change->booking-price#update' }, style: "background-color: transparent; border: none; text-align: center;", min: Date.today }, wrapper_html: { class: 'mb-0 pb-3 border-end', style: 'margin-bottom: 0 !important'} %>
            <%= f.input :end_time, placeholder: (Date.today + 1).to_s, as: :string,  input_html: { value: Date.today, data: { controller: "datepicker", booking_price_target: 'end_date', action: 'change->booking-price#update' }, style: "background-color: transparent; border: none; text-align: center;", min: Date.today } %>

          </div>
          <%= f.submit class: "reserve-btn", value: 'Reserve' %>
        <% end %>
      </div>
      <p class='mt-1 d-flex align-items-center justify-content-between mb-0'>
        <span data-booking-price-target='info'></span>
        <span class='fw-bold' data-booking-price-target='price'></span>
      </p>
      <!-- Request button -->
      <%# <button type="button" class="btn btn-dark w-100 rounded-4 mt-1">Reserve</button> %>
    </div>
  </div>
  <!-- Review -->
  <%# <div class="mt-2 border"></div>
        <h1>reviews</h1> %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareYourDog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <%= link_to image_tag('share your dog.png', alt: "Share Your Dog Logo", height: '50px'), root_path %>
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
          <%# <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active mt-2" aria-current="page" href="/dogs">All Dogs</a>
              </li>
                <ul class="dropdown-menu"> %>
          <%# <% Dog.all.each do |dog| %>
            <%# <li><%= link_to "#{dog.name}", dog_path(dog), class:"dropdown-item" %></li>
          <%# <% end %>
          <%# </ul>
          </ul> %>
          <% if !user_signed_in? %>
            <%= link_to "All dogs", dogs_path, class: 'nav-link' %>
            <%= link_to "Log in", user_session_path, class: "btn-account"%>
          <% else %>
            <%= link_to "All Dogs", dogs_path, class: 'nav-link' %>
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
            <%= link_to "List Dog", new_dog_path, class: 'nav-link' %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn-account"%>
          <% end %>
        </div>
      </div>
    </nav>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_booking_card.erb
<div class="card-booking">
  <%= image_tag booking.dog.photos.all[0], alt: "Dog"%>
  <div class="card-booking-infos">
    <h2>Booking with <%= link_to "#{booking.dog.name}", dog_path(booking.dog), class:"text-dark" %></h2>
    <p><i class="fa-regular fa-calendar"></i> <strong><%= booking.start_time %></strong> (<%= booking.start_time.strftime('%l:%M %p') %>) to <strong><%= booking.end_time %></strong> (<%= booking.end_time.strftime('%l:%M %p') %>)</p>
    <p>Total Price: ¥<strong><%=booking.total_price %></strong></p>
    <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: 'This will delete this booking, are you sure?' }, class: 'card-remove-link' do %>
      <i class="fa-solid fa-poop"></i>
    <% end %>

   <% case booking.status %>
    <% when "pending" %>
      <span class="badge rounded-pill card-pending-pill">Pending</span>
    <% when "accepted"  %>
      <span class="badge text-bg-success rounded-pill card-pending-pill">Accepted</span>
    <% when "rejected"  %>
      <span class="badge text-bg-danger rounded-pill card-pending-pill">Rejected</span>
    <% when "completed" %>
      <span class="badge text-bg-light rounded-pill card-pending-pill">Completed</span>
    <% end %>

  </div>
</div>

app/views/pages/_button.html.erb
<div class="dog-button">
  <%= link_to '#', class: 'btn btn-light'  %>
</div>

app/views/pages/_card.html.erb
<% if dog %>
  <div class="dog_card">
    <div class="card mt-3 m-1 rounded-4">
      <div class="card-body p-0">
        <%# <%= image_tag dog.photos.all[0], alt: "Dog picture", class: "card-img img-fluid" %>
        <%= render 'pages/carousel', dog: dog, class: "card-img img-fluid" %>
      </div>
      <div class="bio ms-2 mt-3 dog_card">
        <p class="mb-0 black-bold"> <strong><%= dog.name %></strong> </p>
        <p class="mb-0"> <%="#{dog.user.name}'s Dog" %></p>
        <p class="black-semi-bold">¥<%=dog.price%>0 per hour</p>
      </div>
    </div>
    <%= link_to "", dog_path(dog), class: "card-dog-link" %>
  </div>
<% end %>

app/views/pages/_card_home.html.erb
<div class="card_index" data-dog-name="<%= dog.name %>" data-dog-description="<%= dog.description %>" data-action="click->home#displayDog">
  <div class="card m-1 rounded-4">
    <div class="card-body p-0">
      <%= image_tag dog.photos.all[0], alt: "Dog picture", class: "card-img img-fluid" %>
    </div>
  </div>
</div>

app/views/pages/_carousel.erb
<% if dog %>
  <div id="carouselExampleIndicators-<%= dog.id %>" class="carousel slide">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators-<%= dog.id %>" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators-<%= dog.id %>" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators-<%= dog.id %>" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
      <%= cl_image_tag dog.photos[0].key, alt: "..." , class: "card-img img-fluid"%>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag dog.photos[1].key, alt: "...", class: "card-img img-fluid" %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag dog.photos[2].key, alt: "...", class: "card-img img-fluid" %>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators-<%= dog.id %>" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators-<%= dog.id %>" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
<% end %>

app/views/pages/_index_card.html.erb
<div class="card_index mb-3">
  <%= render 'pages/carousel', dog: dog, class: "card-img img-fluid index-carousel" %>
  <div class="bio ms-2 mt-3 dog_card">
    <p class="mb-0 black-bold"> <strong><%= dog.name %></strong> </p>
    <p class="mb-0"> <%="#{dog.user.name}'s Dog" %></p>
    <p class="black-semi-bold">¥<%=dog.price%>0 per hour</p>
  </div>
  <%= link_to "", dog_path(dog), class: "card-dog-link" %>
</div>

app/views/pages/_search.html.erb
<div class="input-group mb-3">
  <input type="text" class="form-control search_bar" placeholder="Search a dog to rent..." aria-label="Recipient's username" aria-describedby="button-addon2">
</div>

app/views/pages/home.html.erb
<div class="d-flex justify-content-between" style="height: calc(100vh - 70px)">
  <div class="left d-flex flex-column text-center align-items-center w-50" style="background: url(<%= asset_path 'bg.jpg' %>)">
    <h1 style="font-size: 80px; font-weight: bold; margin-top: 250px; color: white;">BarkBnB</h1>
    <p style="color: white;">Your Best Friend, One Bark at a Time</p>
    <div class="custom-search" style="margin-bottom: 350px;">
      <%= form_with url: dogs_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query, params[:query], class: "custom-search-input", placeholder: "Search a dog to rent..." %>
        <%= button_tag type: "submit", class: "custom-search-botton" do %>
          <i class="fa-solid fa-dog"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="right d-flex flex-column justify-content-between w-50" data-controller="home">
    <div class="main-text pe-5" style="margin-top: 10%; margin-left: 5%">
      <h2 style="font-size: 60px;" data-home-target="meetDog">Meet Our Dogs.</h2>
      <p data-home-target="dogPara">From playful pups to wise seniors, each canine resident boasts a unique personality and a wagging tail eager to greet you. Whether you're seeking a spirited playmate for outdoor adventures or a cuddly couch companion for cozy evenings, our diverse collection of dogs offers something for every dog lover.</p>
    </div>
    <div class="d-flex dogs justify-content-center mx-3" style="margin-bottom: 20%">
      <div data-home-target="dogOne"><%= render 'pages/card_home', dog: @dogs[0] %></div>
      <div data-home-target="dogTwo"><%= render 'pages/card_home', dog: @dogs[1] %></div>
      <div data-home-target="dogThree"><%= render 'pages/card_home', dog: @dogs[3] %></div>
      <div class="row w-100 d-none" data-home-target="showDog">
        <div class="col-6">
          <!-- This section will display the clicked dog card -->
        </div>
        <div class="col-6 shadow-sm p-3">
          <p data-home-target="dogDescription"><%= @dogs[0].description %></p>
          <%= link_to "Back", root_path, class: "reserve-btn" %>
          <%= link_to "Rent Dog", dog_path(@dogs[0]), class: "reserve-btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home_temp.html.erb
<div class="row w-100">
  <div class="col-6">
    <div data-home-target="dogOne"><%= render 'pages/card_home', dog: @dogs[0] %></div>
  </div>
  <div class="col-6">
    <p><%=@dogs[0].description%></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/users/bookings.html.erb
<h1>Users#bookings</h1>
<p>Find me in app/views/users/bookings.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>